String _bdfdAutocompleteSnippet(String name) {
  final custom = _bdfdAutocompleteCustomTemplates[name];
  if (custom != null) {
    return custom;
  }
  if (_bdfdAutocompleteBareFunctions.contains(name)) {
    return String.fromCharCode(36) + name;
  }
  return '${String.fromCharCode(36)}$name[]';
}

final Map<String, String> bdfdAutocompleteTemplates =
    Map<String, String>.unmodifiable(<String, String>{
      for (final name in _bdfdAutocompleteFunctionNames)
        name: _bdfdAutocompleteSnippet(name),
    });

const Map<String, String> _bdfdAutocompleteCustomTemplates = <String, String>{
  'addfield': r'$addField[]',
  'author': r'$author[]',
  'authoravatar': r'$authorAvatar',
  'authorbanner': r'$authorBanner',
  'authorid': r'$authorID',
  'authorusername': r'$authorUsername',
  'authortag': r'$authorTag',
  'channelid': r'$channelID',
  'channelname': r'$channelName',
  'channelsendmessage': r'$channelSendMessage[]',
  'channeltype': r'$channelType',
  'commandname': r'$commandName',
  'commandtype': r'$commandType',
  'customid': r'$customID',
  'description': r'$description[]',
  'displayname': r'$displayName',
  'dmchannelid': r'$dmChannelID',
  'else': r'$else',
  'elseif': r'$elseif[]',
  'endif': r'$endif',
  'endfor': r'$endfor',
  'endloop': r'$endloop',
  'footer': r'$footer[]',
  'for': r'$for[]',
  'forblock': '\$for[]\n\n\$endfor',
  'ifblock': '\$if[]\n\$endif',
  'ifelse': '\$if[]\n\$else\n\$endif',
  'ifelseif': '\$if[]\n\$elseif[]\n\$else\n\$endif',
  'getbotinvite': r'$getBotInvite',
  'getchannelvar': r'$getChannelVar[]',
  'getcustomstatus': r'$getCustomStatus',
  'getmemberscount': r'$getMembersCount',
  'getservervar': r'$getServerVar[]',
  'gettimestampms': r'$getTimestampMs',
  'getuservar': r'$getUserVar[]',
  'getuserstatus': r'$getUserStatus',
  'guildicon': r'$guildIcon',
  'guildid': r'$guildID',
  'guildname': r'$guildName',
  'httpget': r'$httpGet[]',
  'httppost': r'$httpPost[]',
  'image': r'$image[]',
  'isuserdmenabled': r'$isUserDMEnabled',
  'jsonparse': r'$jsonParse[]',
  'lastmessageid': r'$lastMessageID',
  'loop': r'$loop[]',
  'loopblock': '\$loop[]\n\n\$endloop',
  'membercount': r'$memberCount',
  'messageeditedtimestamp': r'$messageEditedTimestamp',
  'messageid': r'$messageID',
  'messagetimestamp': r'$messageTimestamp',
  'messagetype': r'$messageType',
  'messageurl': r'$messageURL',
  'mentionedroles': r'$mentionedRoles',
  'onlyif': r'$onlyIf[]',
  'parentid': r'$parentID',
  'reply': r'$reply[]',
  'repliedmessageid': r'$repliedMessageID',
  'ruleschannelid': r'$rulesChannelID',
  'sendmessage': r'$sendMessage[]',
  'servercount': r'$serverCount',
  'servericon': r'$serverIcon',
  'serverid': r'$serverID',
  'servername': r'$serverName',
  'servernames': r'$serverNames',
  'setchannelvar': r'$setChannelVar[]',
  'setservervar': r'$setServerVar[]',
  'setuservar': r'$setUserVar[]',
  'slashcommandscount': r'$slashCommandsCount',
  'slashid': r'$slashID',
  'systemchannelid': r'$systemChannelID',
  'thumbnail': r'$thumbnail[]',
  'title': r'$title[]',
  'useravatar': r'$userAvatar',
  'userbanner': r'$userBanner',
  'userbannercolor': r'$userBannerColor',
  'userid': r'$userID',
  'userroles': r'$userRoles',
  'userserveravatar': r'$userServerAvatar',
  'usertag': r'$userTag',
};

const Set<String> _bdfdAutocompleteBareFunctions = <String>{
  'alternativeparsing',
  'allmemberscount',
  'argcount',
  'authoravatar',
  'authorbanner',
  'authorid',
  'authorofmessage',
  'authorusername',
  'authortag',
  'blacklistids',
  'blacklistroleids',
  'blacklistroles',
  'blacklistrolesids',
  'blacklistservers',
  'blacklistusers',
  'botcommands',
  'botcount',
  'botid',
  'botlisthide',
  'botlistdescription',
  'botname',
  'botnode',
  'botownerid',
  'boostcount',
  'boostlevel',
  'c',
  'categorychannels',
  'categorycount',
  'categoryid',
  'channelcategoryid',
  'channelcount',
  'channelexists',
  'channelid',
  'channelidfromname',
  'channelname',
  'channelnames',
  'channelnsfw',
  'channelposition',
  'channeltopic',
  'channeltype',
  'commandfolder',
  'commandname',
  'commandscount',
  'commandtrigger',
  'commandtype',
  'creationdate',
  'customid',
  'date',
  'day',
  'deletecommand',
  'disableinnerspaceremoval',
  'disablespecialescaping',
  'discriminator',
  'displayname',
  'dmchannelid',
  'else',
  'enabled',
  'endif',
  'endfor',
  'endloop',
  'enabledecimals',
  'error',
  'executiontime',
  'findchannel',
  'finduser',
  'getbotinvite',
  'getcustomstatus',
  'getinviteinfo',
  'getmemberscount',
  'getserverinvite',
  'gettimestamp',
  'gettimestampms',
  'getuserstatus',
  'guildbanner',
  'guildcount',
  'guildexists',
  'guildicon',
  'guildid',
  'guildname',
  'highestrole',
  'highestrolewithperms',
  'hypesquad',
  'i',
  'ignorelinks',
  'isadmin',
  'isbooster',
  'isbot',
  'isslash',
  'isticket',
  'isuserdmenabled',
  'lastmessageid',
  'lastpintimestamp',
  'loopcount',
  'loopindex',
  'loopiteration',
  'lowestrole',
  'lowestrolewithperms',
  'membercount',
  'memberid',
  'membernick',
  'messageid',
  'messagetimestamp',
  'messagetype',
  'messageurl',
  'minute',
  'month',
  'nickname',
  'nomention',
  'nomentionmessage',
  'onlinemembers',
  'optoff',
  'parentid',
  'ping',
  'premiumexpiretime',
  'randomcategoryid',
  'randomchannelid',
  'randomguildid',
  'randommention',
  'randomroleid',
  'randomuser',
  'randomuserid',
  'registerguildcommands',
  'repliedmessageid',
  'rolecount',
  'rolenames',
  'ruleschannelid',
  'scriptlanguage',
  'second',
  'serverbanner',
  'serverboostcount',
  'serverchannelexists',
  'servercount',
  'serverdescription',
  'serveremojis',
  'serverfeatures',
  'servericon',
  'serverid',
  'serverinfo',
  'servername',
  'servernames',
  'serverowner',
  'serverregion',
  'serversplash',
  'servervanityurl',
  'serververificationlevel',
  'serververificationlvl',
  'shardid',
  'slashcommandscount',
  'slashid',
  'stickercount',
  'stop',
  'systemchannelid',
  'threadmessagecount',
  'threadusercount',
  'time',
  'unregisterguildcommands',
  'uptime',
  'url',
  'useravatar',
  'userbadges',
  'userbanner',
  'userbannercolor',
  'userexists',
  'userinfo',
  'userid',
  'userjoined',
  'userjoineddiscord',
  'userperms',
  'userroles',
  'userserveravatar',
  'usertag',
  'username',
  'usersinchannel',
  'variablescount',
  'varexisterror',
  'voiceuserlimit',
  'webhookavatarurl',
  'webhookcolor',
  'webhookcontent',
  'webhookdescription',
  'webhookfooter',
  'webhooktitle',
  'webhookusername',
  'year',
};

const Set<String> _bdfdAutocompleteFunctionNames = <String>{
  ..._bdfdAutocompleteBareFunctions,
  'addbutton',
  'forblock',
  'ifblock',
  'ifelse',
  'ifelseif',
  'loopblock',
  'addcmdreactions',
  'addcontainer',
  'addmediagallery',
  'addemoji',
  'addfield',
  'addmessagereactions',
  'addreactions',
  'addsection',
  'addselectmenuoption',
  'addseparator',
  'addtextdisplay',
  'addtextinput',
  'addthumbnail',
  'addtimestamp',
  'allowmention',
  'allowrolementions',
  'allowusermentions',
  'args',
  'argscheck',
  'author',
  'authoricon',
  'authorurl',
  'awaitfunc',
  'ban',
  'banid',
  'botleave',
  'bottyping',
  'bytecount',
  'calculate',
  'callworkflow',
  'ceil',
  'changecooldowntime',
  'changeusername',
  'changeusernamewithid',
  'channelsendmessage',
  'charcount',
  'checkcondition',
  'checkcontains',
  'checkuserperms',
  'checkusersperms',
  'clear',
  'clearreactions',
  'closeticket',
  'color',
  'colorrole',
  'contains',
  'cooldown',
  'createchannel',
  'createrole',
  'croptext',
  'customemoji',
  'defer',
  'deletechannels',
  'deletechannelsbyname',
  'deletein',
  'deletemessage',
  'deleterole',
  'description',
  'divide',
  'dm',
  'editbutton',
  'editchannelperms',
  'editembedin',
  'editin',
  'editmessage',
  'editselectmenu',
  'editselectmenuoption',
  'editsplittext',
  'editthread',
  'elseif',
  'embeddedurl',
  'embedsuppresserrors',
  'emojicount',
  'emojiexists',
  'emojiname',
  'emotecount',
  'ephemeral',
  'equals',
  'eval',
  'findrole',
  'floor',
  'footer',
  'footericon',
  'for',
  'getattachments',
  'getbanreason',
  'getchannelvar',
  'getcooldown',
  'getembeddata',
  'getguildmembervar',
  'getguildvar',
  'getleaderboardposition',
  'getleaderboardvalue',
  'getmembervar',
  'getmessage',
  'getmessagevar',
  'getreactions',
  'getrolecolor',
  'getservervar',
  'gettextsplitindex',
  'gettextsplitlength',
  'getuservar',
  'getvar',
  'giverole',
  'giveroles',
  'globalcooldown',
  'globaluserleaderboard',
  'hasrole',
  'hostingexpiretime',
  'httpaddheader',
  'httpdelete',
  'httpget',
  'httppatch',
  'httppost',
  'httpput',
  'httpresult',
  'httpstatus',
  'if',
  'ignorechannels',
  'image',
  'input',
  'isbanned',
  'isboolean',
  'isemojianimated',
  'ishoisted',
  'isinteger',
  'ismentioned',
  'ismessageedited',
  'ismentionable',
  'isnsfw',
  'isnumber',
  'istimedout',
  'isvalidhex',
  'joinsplittext',
  'json',
  'jsonarray',
  'jsonarrayappend',
  'jsonarraycount',
  'jsonarrayindex',
  'jsonarraypop',
  'jsonarrayreverse',
  'jsonarrayshift',
  'jsonarraysort',
  'jsonarrayunshift',
  'jsonclear',
  'jsonexists',
  'jsonjoinarray',
  'jsonparse',
  'jsonpretty',
  'jsonset',
  'jsonsetstring',
  'jsonstringify',
  'jsonunset',
  'kick',
  'kickmention',
  'linescount',
  'loop',
  'max',
  'mentioned',
  'mentionedchannels',
  'message',
  'min',
  'modifychannel',
  'modifychannelperms',
  'modifyrole',
  'modifyroleperms',
  'modulo',
  'multi',
  'mute',
  'newmodal',
  'newselectmenu',
  'newticket',
  'numberseparator',
  'onlyadmin',
  'onlybotchannelperms',
  'onlybotperms',
  'onlyforcategories',
  'onlyforchannels',
  'onlyforids',
  'onlyforroleids',
  'onlyforroles',
  'onlyforservers',
  'onlyforusers',
  'onlyif',
  'onlyifmessagecontains',
  'onlynsfw',
  'onlyperms',
  'pinmessage',
  'publishmessage',
  'random',
  'randomstring',
  'randomtext',
  'removeallcomponents',
  'removebuttons',
  'removecomponent',
  'removecontains',
  'removeemoji',
  'removelinks',
  'removesplittextelement',
  'repeatmessage',
  'replacetext',
  'reply',
  'replyin',
  'resetchannelvar',
  'resetguildmembervar',
  'resetguildvar',
  'resetmembervar',
  'resetservervar',
  'resetuservar',
  'roleexists',
  'rolegrant',
  'roleid',
  'roleinfo',
  'rolename',
  'roleperms',
  'roleposition',
  'round',
  'sendembedmessage',
  'sendmessage',
  'servercooldown',
  'serverleaderboard',
  'setchannelvar',
  'setguildmembervar',
  'setguildvar',
  'setmembervar',
  'setmessagevar',
  'setservervar',
  'setuserroles',
  'setuservar',
  'setvar',
  'slowmode',
  'sort',
  'splittext',
  'sqrt',
  'startthread',
  'sub',
  'sum',
  'suppresserrors',
  'takerole',
  'takeroles',
  'textsplit',
  'threadaddmember',
  'threadremovemember',
  'thumbnail',
  'timeout',
  'title',
  'tolowercase',
  'totitlecase',
  'touppercase',
  'trimcontent',
  'trimspace',
  'tts',
  'unban',
  'unbanid',
  'unescape',
  'unmute',
  'unpinmessage',
  'untimeout',
  'usechannel',
  'userleaderboard',
  'userreacted',
  'userswithrole',
  'var',
  'varexists',
  'webhookcreate',
  'webhookdelete',
  'webhooksend',
  'workflowresponse',
};
